heat_template_version: 2013-05-23

description: Template that assigns a floating IP address to vsrx

parameters:
  port:
    type: string
    label: Server port
    description: The server port that receives the floating IP address.

  public_network:
    type: string
    label: Public network name or ID
    description: Public network with floating IP addresses.

resources:
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_param: port }

outputs:
  ip:
    description: The floating IP address assigned to the server.
    value: { get_attr: [floating_ip, floating_ip_address] }
