heat_template_version: 2013-05-23

description: >
  HOT template for PyEZ InstallConfig

parameters:
  host:
    type: string
    description: IP address/name of JUNOS target

  user:
    type: string
    description: user name

  password:
    type: string
    description: password

  file:
    type: string
    description: config file path

  overwrite:
    type: number
    description: Overwrite or merge
    default: 0

  logfile:
    type: string
    description: logfile path
    default: /root/pyez-heat/logs/pyez.log

  diffs_file:
    type: string
    description: diffs_file path
    default: /root/pyez-heat/logs/pyez_diff_file

  savedir:
    type: string
    description: directory to save device facts
    default: /root/pyez-heat/logs/

  timeout:
    type: number
    description: NETCONF RPC timeout
    default: 0

  comment:
    type: string
    description: comment for commit operation

  port:
    type: number
    description: TCP port on device
    default: 830

  check_mode:
    type: number
    description: Check mode for commit
    default: 0

resources:
  junos_config:
    type: OS::PyEZ::InstallConfig
    properties:
      host: { get_param: host }
      user: { get_param: user }
      password: { get_param: password }
      file: { get_param: file }
      overwrite: { get_param: overwrite }
      logfile: { get_param: logfile }
      diffs_file: { get_param: diffs_file }
      savedir: { get_param: savedir }
      timeout: { get_param: timeout }
      comment: { get_param: comment }
      port: { get_param: port }
      check_mode: { get_param: check_mode }

