heat_template_version: 2013-05-23

description: Template to deploy a single vsrx instance

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
# key:
#   type: string
#   label: Key name
#   description: Name of key-pair to be used for compute instance
#   default: vsrx_key
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
#     key_name: { get_param: key }
      networks:
        - network: { get_param: private_network }

outputs:
  instance_name:
    description: Name of the instance
    value: { get_attr: [my_instance, name] }
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [my_instance, first_address] }
